[package]
name = "ray-tracer-mini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "raytracer"
path = "src/lib/mod.rs"

[dependencies]
derive_more = "0.99.17"
