# Configuration for the Image to be rendered
img_width = 400
img_height = 225
depth = 50
samples = 100

# "random spheres", "two spheres", "two perlin spheres"
#scene = "two perlin spheres"
scene = "two perlin spheres"
